Updates TriG grammar to be consistent with Turtle.
w3c/rdf-trig pull request #38
Opened 2024-10-24 21:25 UTC by gkellogg

2024-10-24 21:46 UTC, domel approved these changes

2024-10-24 22:35 UTC, TallTed requested changes

2024-10-24 22:35 UTC, TallTed commented on spec/index.html
> +        <a href="#grammar-production-ttObject"><code>rtObject</code></a>, and
```suggestion
        <a href="#grammar-production-rtObject"><code>rtObject</code></a>, and
```

2024-10-27 10:54 UTC, afs approved these changes

2024-10-27 16:18 UTC, merged